// Customers
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const REMOVE_CUSTOMER_SUCCESS = 'REMOVE_CUSTOMER_SUCCESS';

export const START_FETCHING = 'START_FETCHING';
export const DONE_FETCHING = 'DONE_FETCHING';


// Timesheets
export const TIMESHEETS_ADD = 'TIMESHEETS_ADD';
export const TIMESHEETS_ADD_SUCCESS = 'TIMESHEETS_ADD_SUCCESS';
export const TIMESHEETS_REMOVE = 'TIMESHEETS_REMOVE';
export const TIMESHEETS_REMOVE_SUCCESS = 'TIMESHEETS_REMOVE_SUCCESS';

export const TIMESHEETS_START_FETCHING = 'TIMESHEETS_START_FETCHING';
export const TIMESHEETS_DONE_FETCHING = 'TIMESHEETS_DONE_FETCHING';
