// Customers
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const REMOVE_CUSTOMER_SUCCESS = 'REMOVE_CUSTOMER_SUCCESS';

export const START_FETCHING = 'START_FETCHING';
export const DONE_FETCHING = 'DONE_FETCHING';
